name: Check

on:
  push:
jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: iseki0/idea-download-action@master

      - name: Reformat
        run: format -r -m *.kt,*.kts,*.java .

      - name: Check
        run: git diff --exit-code --color

